### ISSUE TITLE
Override the type of setting

### ISSUE THREAD

**Issue by YulKard** [adminarchitect/options#1]
Good afternoon!
Tell me, how can I override the type of field in the settings? For example, with text on select?
Code with description

> public function form()
{
    return array_merge(
        $this->scaffoldForm(),
        [
            'ssl' => ['type' => 'boolean', 'label' => 'Use SSL'],
        ]
    );
}

return a mistake http://joxi.ru/DmBDWDWSwkZG1A. 

Plus options are not saved after editing
  http://joxi.ru/5mdMjMjukQVwd2
saving  http://joxi.ru/L21bnbnu8NyddA

Can someone encounter such a problem? What in this case do? Thank you.

**Comment by endihunter** [comment]
that is because you mix up the old-style with a new one:
in your case the form method should be something like this:

```php
public function form()
{
    return $this
        ->scaffoldForm()
        ->update('ssl', function (FormElement $element) {
            return tap($element, function ($element) {
                $element->setInput(new Boolean('ssl'));
            });
        });
}
```

**Comment by YulKard** [comment]
Thank you. 
I think that in this case ->update('ssl' ) must  be a name of columns, but not a value of field (see in documentation Forms) . 
It turns out, I can also rename the field name for output in the admin panel?

**Comment by endihunter** [comment]
in my example, I've shown you - the 'ssl' is a field name, not a value

**Comment by YulKard** [comment]
Sorry, Yes, I meant the name of the field. 

I was able to change the types of fields and their names, but the problem with saving still remains. After editing, the data is not saved, the old values remain. I use HasOptions. Which way should I look?
If you output the output to a form, all the data is saved.

**Comment by endihunter** [comment]
just finished playing with options module (default configuration):
my Settings module: https://gist.github.com/endihunter/3c5ac84c420f02d5949a8e80272657e7
it has 2 text fields, 1 boolean & 1 dropdown - everything works well. 
Maybe you can provide me your columns & form() method so I'd be able to help you.

**Comment by YulKard** [comment]
I did not work saving as soon as I installed the module. Here is my module
`<?php
namespace App\Http\Terranet\Administrator\Modules;

use Terranet\Options\Option;
use Terranet\Administrator\Scaffolding;
use Terranet\Administrator\Traits\Module\HasOptions;
use Terranet\Administrator\Contracts\Module\Editable;
use Terranet\Administrator\Contracts\Module\Navigable;
use Terranet\Administrator\Contracts\Module\Validable;
use Terranet\Administrator\Traits\Module\ValidatesOptions;

class Settings extends Scaffolding implements Navigable, Editable, Validable
{

    use HasOptions,
        ValidatesOptions;

    protected $model = Option::class;

    /**
     * The module url
     *
     * @return mixed
     */
    public function url()
    {
        return 'settings';
    }

    /**
     * The module title
     *
     * @return mixed
     */
    public function title()
    {
        return trans("administrator::module.resources.settings");
    }

    /**
     * Navigation group which Resource belongs to
     *
     * @return string
     */
    public function group()
    {
        return null;
    }

    /**
     * Navigation container which Resource belongs to
     * Available: sidebar, tools
     *
     * @return mixed
     */
    public function navigableIn()
    {
        return Navigable::MENU_TOOLS;
    }

    public function linkAttributes()
    {
        return ['icon' => 'fa fa-gears'];
    }
}`

**Comment by YulKard** [comment]
Thanks for the help. I'm now trying to reinstall the module and check it again.
